import os

path = os.getcwd() + '/Tests/Resources/SuccessRateResources/'

pictures = {path + 'blackfacefemale.jpg': 1,
            path + 'fourfaces.png': 4,
            path + 'blackfacemale.jpeg': 1,
            path + 'face_in_circle.jpeg': 5,
            path + 'five_people_looking_down.jpg': 5,
            path + 'four_babies.jpg': 4,
            path + 'oneFace.jpeg': 1,
            path + 'oneFace.jpg': 1,
            path + 'OneFace.jpeg': 1,
            path + 'SevenBlackPeople.jpg': 7,
            path + 'SixFaces.jpeg': 6,
            path + 'thirteen_people_smileing.jpg': 13,
            path + 'thirteen_babies_in_circle.jpg': 13,
            path + 'FourPeopleFamilyBlack.jpg': 4,
            path + 'SevenDifferantPeople.jpg': 7,
            path + 'eightPeopleSmiling.jpg': 8,
            path + 'fiveFriends.jpg': 5,
            path + 'twentyfourpeople.jpg': 24,
            path + 'twoPeople.jpg': 2,
            path + 'fifteenpeople.jpg': 15,
            path + 'tenPeople.jpeg': 10,
            path + 'fourPeople.jpg': 4,
            path + 'sixPeople.jpg': 6,
            path + 'fourPeopleFamily.jpg': 4,
            path + 'thirteenPeople.jpg': 13,
            path + 'threePeople.jpeg': 3,
            path + 'twoPeople.jpeg': 2,
            path + 'fourPeopleIndiaFamily.jpg': 4,
            path + 'fourAsians.jpeg': 4,
            path + 'fiveAsians.jpg': 5,
            path + 'sixLatin.jpg': 6,
            path + 'nineAfrican.jpg': 9,
            path + 'twentyAfrican.jpg': 20,
            path + 'sixRussians.jpg': 6,
            path + 'eithGermans.jpg': 8,
            path + 'eithBrazilians.jpg': 8,
            path + 'sixTurkish.jpg': 6,
            path + 'sixUAEFamily.jpg': 6,
            path + 'fiveArabs.jpg': 5,
            path + 'nineMongolian.jpg': 9,
            path + 'thirteenMongolians.jpg': 13,
            path + 'tenIraqs.jpg': 10,
            path + 'sixTurkishFamily.jpg': 6,
            path + 'Elizabeth.jpg': 1,
            path + 'threeKidsWithHats.jpg': 3,
            path + 'fivePeopleSunglasses.jpg': 5,
            path + 'fourPeopleSunglasses.jpg': 4,
            path + 'twoFacesGlassesandNo.jpg': 2,
            path + 'tenPeopleGlasses.jpeg': 10,
            path + 'oneUnderwater.jpg': 1}

path_to_picture = list(pictures.keys())
number_of_faces = list(pictures.values())
